### ISSUE TITLE
Al endpoint POST /favorites/<int:user_id>/planet/<int:planet_id> no funciona

### ISSUE THREAD

**Issue by StefAranzazu** [JoseLike/Stars-Wars-API#10]
Tienes que serializar lo retornado
![image](https://user-images.githubusercontent.com/84442570/167834982-623be522-e5cc-4887-8a1f-bbb510935108.png)

**Comment by StefAranzazu** [comment]
Igual en el endpoint que agrega personajes favoritos

**Comment by JoseLike** [comment]
solucionado
