### ISSUE TITLE
Al llamarlo planet.serialize, da error

### ISSUE THREAD

**Issue by StefAranzazu** [JoseLike/Stars-Wars-API#2]
Cámbiale el nombre y ya funcionaria bien, tanto en la línea 47 como en la 48

![image](https://user-images.githubusercontent.com/84442570/167246919-19f7516f-5098-4777-9cbe-4a9030187928.png)

**Comment by StefAranzazu** [comment]
Lo mismo pasa con los planetas, favoritos, users y los vehículos

**Comment by JoseLike** [comment]
Modificado!. Probar nuevamente
